function (USE_14)
	message(STATUS "Using C++14")
	set(CPP14 "-std=c++14")
	set(CMAKE_CXX_FLAGS "${CPP14} ${CMAKE_CXX_FLAGS}")
endfunction()
function (USE_11)
	message(STATUS "Using C++11")
	set(CPP14 "-std=c++11")
	set(CMAKE_CXX_FLAGS "${CPP11} ${CMAKE_CXX_FLAGS}")
endfunction()

